/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Atom(props) {
  const { nodes, materials } = useGLTF("/atom_3D.glb");
  // console.log(nodes)
  console.log(nodes.node_id30);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.node_id30.geometry}
        material={materials["47"]}
        position={[0, 0, 0]}
        rotation={[0.2535, 0.2958, 0.8443]}
        scale={0.0513}
      />
    </group>
  );
}

useGLTF.preload("/atom_3D.glb");
